### ISSUE TITLE
Unable to start video streams

### ISSUE THREAD

**Issue by Geosearchef** [hubsif/kodi-telekomsport#17]
I'm not able to start streams. ("see log for further information")
Sometimes the listing for the stream vanishes midgame aswell.

```
19:51:27.905 T:1926027776   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10617]
19:51:29.158 T:1669329664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.telekomsport/default.py", line 325, in <module>
                                                locals()['get' + mode]()
                                              File "/home/osmc/.kodi/addons/plugin.video.telekomsport/default.py", line 277, in getvideo
                                                jwt = get_jwt(_addon.getSetting('username'), _addon.getSetting('password'))
                                              File "/home/osmc/.kodi/addons/plugin.video.telekomsport/default.py", line 72, in get_jwt
                                                jsonResult = json.loads(response)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
19:54:32.931 T:1180693248 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10617
```

Kodi version:
```
17:59:37.290 T:1926027776  NOTICE: Starting Kodi (17.6). Platform: Linux ARM (Thumb) 32-bit
17:59:37.290 T:1926027776  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
17:59:37.290 T:1926027776  NOTICE: Kodi compiled Feb  4 2018 by GCC 6.3.0 for Linux ARM (Thumb) 32-bit version 4.9.30 (264478)
```

**Comment by MRLB** [comment]
Gleiche Problem. Abundzu funktioniert erst der 10. Versuch. System: Android

**Comment by hubsif** [comment]
Hi. Ich konnte das Problem nachstellen, da die Streams bei mir jetzt auch nicht mehr funktioniert haben.
Ich denke, ich habe es auch gefixt, es hatte mit der Authentifizierung bei der Telekom zu tun, möglicherweise haben die was geändert.
Allerdings bekomme ich jetzt auch das Problem, das zuletzt in #8 geschildert wurde, nämlich dass ein Popup eines vorherigen Fehlers das Bild überlagert. Das werde ich mir bei nächster Gelegenheit genauer ansehen, bevor ich eine neue Version erstelle.

Wer möchte, kann in der Zwischenzeit den Fix mal selbst ausprobieren, vielleicht funktioniert es ja bei euch ohne Popup-Problem. Dazu in der Datei `default.py` die Zeile 71:
    
    response = urllib.urlopen(oauth_url + '?' + urllib.urlencode(data), "").read()

in:

    response = urllib2.urlopen(urllib2.Request(oauth_url, urllib.urlencode(data), {'Content-Type': 'application/json'})).read()

ändern.

**Comment by MRLB** [comment]
Perfekt. Damit geht zumindest BayernTV wieder. Die anderen Livestreams werde ich morgen testen :-)

**Comment by hubsif** [comment]
Dieses Problem hier war wohl nur vorübergehend, denn die vorgeschlagene Änderung brauchte es dann gar nicht mehr. Ich hab sie jetzt dennoch in die v1.2.2 eingepflegt.
